language: ruby
cache: bundler
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
gemfile:
  - gemfiles/rubocop_0.49.0.gemfile # The oldest version in the supported versions
  - gemfiles/rubocop_0.61.1.gemfile # The newest version in the supported versions
  - gemfiles/rubocop_head.gemfile
matrix:
  include:
  allow_failures:
    - gemfile: gemfiles/rubocop_head.gemfile
  fast_finish: true
