language: ruby
cache: bundler
rvm:
  - 2.3.3
  - 2.4.1
  - ruby-head
gemfile:
  - gemfiles/rubocop_0.48.1.gemfile
  - gemfiles/rubocop_0.47.1.gemfile
  - gemfiles/rubocop_head.gemfile
matrix:
  include:
  allow_failures:
    - gemfile: gemfiles/rubocop_head.gemfile
  fast_finish: true
